name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build sources 
        run: npm run build
      - name: Lint sources
        run: npm run lint
      - name: Run tests
        run: npm test -- --coverage
      - name: Upload coverage results
        continue-on-error: true
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage/clover.xml
